name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: src
    
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: msbuild build -c Release
    - name: Publish
      run: dotnet publish -c Release -o "${{ github.workspace }}/publish"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: WebsiteChangeDetector
        path: |
          ${{ github.workspace }}/publish
          ${{ github.workspace }}/WebsiteChangeDetector.Database/bin/Release/WebsiteChangeDetector.Database.dacpac
